title: Sudipt Sharma
description: Hi I am DevOps Specialist and a creative professional who has extensive knowledge of DevOps solutions and opensource tools. I am specialized in cloud computing, with a penchant for AWS.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman